### ISSUE TITLE
[Enhancement Reques] Use world.InternalName for KR/CN Compatibility

### ISSUE THREAD

**Issue by LittleNightmare** [kalilistic/Dalamud.DrunkenToad#4]
i am currently facing compatibility issues with the `PlayerTrack` in the CN region, specifically related to the validation of HomeWorld with CommonLists. the use of `world.Name` as below is causing these validations to fail, and i believe that switching to `world.InternalName` could resolve these issues while maintaining global compatibility.

https://github.com/kalilistic/Dalamud.DrunkenToad/blob/32f38b988d2767eb9dfee49bb34524392a42b800/Core/Services/Ex/DataManagerEx.cs#L211-L216

**Comment by kalilistic** [comment]
This seems to work okay. I've updated the library and ptrack too (pending merge).

**Comment by LittleNightmare** [comment]
THANKS! it works
